config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.name = params[:post][:name]
    @post.title = params[:post][:title]
    @post.content = params[:post][:content]
    @post.save
    
    redirect_to '/'
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.name = params[:post][:name]
    @post.title = params[:post][:title]
    @post.content = params[:post][:content]
    @post.save
    
    redirect_to '/'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to '/'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

app/views/homes/destroy.html.erb
<h1>Homes#destroy</h1>
<p>Find me in app/views/homes/destroy.html.erb</p>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

<%= form_for @post, url: home_path, method: "PATCH" do |f| %>
    새 작성자: <%= f.text_field :name %> <br>
    새 제목: <%= f.text_field :title %> <br>
    새 내용: <%= f.text_area :content %> <br>

    <%= f.submit "수정완료" %>
<% end %>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

<% @posts.each do |p| %>
    작성자: <%= p.name %> 
    제목: <%= p.title %> 
    내용: <%= p.content %> 
    <%= link_to "더 보기", home_path(id: p.id) %>
    <%= link_to "수정하기", edit_home_path(id: p.id) %>
    <%= link_to "삭제하기", home_path(id: p.id), method: "DELETE"%> <br>
    <hr>
<% end %>

<%= link_to "새 글 작성",  new_home_path %>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

<%= form_for @post, url: homes_path, method: "POST" do |f| %>
    작성자: <p> <%= f.text_field :name %> </p>
    제목: <p> <%= f.text_field :title %> </p>
    내용: <p> <%= f.text_area :content, size: '50x10' %> </p>
    <%= f.submit "작성" %>
<% end %>
<!--</form>-->

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

<hr>
작성자: <%= @post.name %> <br>
제목: <%= @post.title %> <br>
내용: <%= @post.content %> <br>

<%= link_to "되돌아가기", homes_path %>
<%= link_to "수정하기", edit_home_path(id: @post.id) %>
<%= link_to "삭제하기", home_path(id: @post.id), method: :DELETE %>

<hr>

app/views/homes/update.html.erb
<h1>Homes#update</h1>
<p>Find me in app/views/homes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithoutScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>